import { nanoid } from "nanoid";
import { IProjectItem } from "../types";

export const projectsData: IProjectItem[] = [
	{
		id: nanoid(),
		img: "/assets/img/entertainment-web-app.webp",
		name: "Entertainment web app",
		techList: [
			"React",
			"Typescript",
			"Tailwind",
			"Zustand",
			"React hook form",
			"Zod",
			"Tanstack query",
			"firebase",
		],
		liveLink: "https://entertainment-web-app-phi-pink.vercel.app/",
		gitRepo: "https://github.com/a1conwf/entertainment-web-app",
	},
	{
		id: nanoid(),
		img: "/assets/img/weather-app.webp",
		name: "Weather app",
		techList: [
			"React",
			"typescript",
			"tailwind",
			"zustand",
			"react hook form",
			"zod",
			"tanstack query",
		],
		liveLink: "https://weather-app-navy-sigma-15.vercel.app/",
		gitRepo: "https://github.com/a1conwf/weather-app",
	},
	{
		id: nanoid(),
		img: "/assets/img/dictionary-web-app.webp",
		name: "Dictionary web app",
		techList: ["React", "typescript", "context api", "tailwind", "shadcn", "zod", "tanstack query"],
		liveLink: "https://dictionary-web-app-theta-lac.vercel.app/",
		gitRepo: "https://github.com/a1conwf/dictionary-web-app",
	},
	{
		id: nanoid(),
		img: "/assets/img/personal-blog.jpg",
		name: "Personal blog",
		techList: ["Astro", "Html", "Tailwind", "Typescript", "Sanity cms"],
		liveLink: "https://personal-blog-astro-app-1hdw.vercel.app/",
		gitRepo: "https://github.com/a1conwf/personal-blog",
	},
	{
		id: nanoid(),
		img: "/assets/img/manage-landing-page.webp",
		name: "Manage Landing Page",
		techList: ["Astro", "Html", "Tailwind", "Javascript"],
		liveLink: "https://manage-landing-page-two-gules.vercel.app/",
		gitRepo: "https://github.com/a1conwf/manage-landing-page",
	},
	{
		id: nanoid(),
		img: "/assets/img/portfolio-website.webp",
		name: "Portfolio Website",
		techList: ["React", "Typescript", "Scss modules", "React hook form", "Zod"],
		liveLink: "https://antonkashuba.dev/",
		gitRepo: "https://github.com/a1conwf/ak-portfolio",
	},
];
