import { nanoid } from "nanoid";
import { IProjectItem } from "../types";

export const projectsData: IProjectItem[] = [
	{
		id: nanoid(),
		img: "/assets/img/entertainment-web-app.webp",
		name: "Entertainment web app",
		techList: [
			"React",
			"Typescript",
			"Tailwind",
			"Zustand",
			"React hook form",
			"Zod",
			"Tanstack query",
			"firebase",
		],
		liveLink: "https://entertainment-web-app-phi-pink.vercel.app/",
		gitRepo: "https://github.com/a1conwf/entertainment-web-app",
	},
	{
		id: nanoid(),
		img: "/assets/img/weather-app.webp",
		name: "Weather app",
		techList: [
			"React",
			"typescript",
			"tailwind",
			"zustand",
			"react hook form",
			"zod",
			"tanstack query",
		],
		liveLink: "https://weather-app-navy-sigma-15.vercel.app/",
		gitRepo: "https://github.com/a1conwf/weather-app",
	},
	{
		id: nanoid(),
		img: "/assets/img/designo-website.webp",
		name: "Designo website",
		techList: ["Next.js", "Typescript", "Tailwind", "React hook form", "Zod"],
		liveLink: "https://designo-website-two.vercel.app/",
		gitRepo: "https://github.com/a1conwf/designo-website",
	},
	{
		id: nanoid(),
		img: "/assets/img/payapi-website.webp",
		name: "Payapi website",
		techList: ["Next.js", "Typescript", "Tailwind", "React hook form", "Zod"],
		liveLink: "https://payapi-website-mu.vercel.app/",
		gitRepo: "https://github.com/a1conwf/payapi-website",
	},
	{
		id: nanoid(),
		img: "/assets/img/personal-blog.jpg",
		name: "Personal blog",
		techList: ["Astro", "Html", "Tailwind", "Typescript", "Sanity cms"],
		liveLink: "https://personal-blog-astro-app-1hdw.vercel.app/",
		gitRepo: "https://github.com/a1conwf/personal-blog",
	},
	{
		id: nanoid(),
		img: "/assets/img/manage-landing-page.webp",
		name: "Manage Landing Page",
		techList: ["Astro", "Html", "Tailwind", "Javascript"],
		liveLink: "https://manage-landing-page-two-gules.vercel.app/",
		gitRepo: "https://github.com/a1conwf/manage-landing-page",
	},
	{
		id: nanoid(),
		img: "/assets/img/digitalbank-landing-page.webp",
		name: "Digitalbank Landing Page",
		techList: ["Html", "Tailwind", "Javascript", "Vite"],
		liveLink: "https://digitalbank-landing-page-olive.vercel.app/",
		gitRepo: "https://github.com/a1conwf/digitalbank-landing-page",
	},
	{
		id: nanoid(),
		img: "/assets/img/portfolio-website.webp",
		name: "Portfolio Website",
		techList: ["React", "Typescript", "Scss modules", "React hook form", "Zod"],
		liveLink: "https://antonkashuba.dev/",
		gitRepo: "https://github.com/a1conwf/ak-portfolio",
	},
];
