import { nanoid } from "nanoid";
import { IProjectItem } from "../types";

export const projectsData: IProjectItem[] = [
  {
    id: nanoid(),
    img: "/src/assets/img/pizza-palace.png",
    name: "Pizza Palace",
    techList: [
      "React",
      "React router",
      "React skeleton",
      "Typescript",
      "Redux Toolkit",
      "Axios",
      "css modules",
    ],
    liveLink: "https://pizza-palace-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/pizza-palace",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/todo-app.webp",
    name: "Todo app",
    techList: ["React", "css modules"],
    liveLink: "https://todo-app-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/todo-app",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/password-generator-app.webp",
    name: "Password Generator App",
    techList: ["React", "css modules"],
    liveLink: "https://password-generator-app-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/password-generator-app",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/gpu-shop.png",
    name: "GPU Online Shop",
    techList: ["React", "React Router", "React Skeleton", "Axios", "Scss"],
    liveLink: "https://gpu-shop.vercel.app/",
    gitRepo: "https://github.com/a1conwf/gpu-shop",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/tip-calculator-app.webp",
    name: "Tip calculator app",
    techList: ["React", "Scss"],
    liveLink: "https://tip-calculator-app-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/tip-calculator-app",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/interactive-pricing-component.webp",
    name: "Interactive pricing component",
    techList: ["React", "Scss"],
    liveLink: "https://interactive-pricing-component-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/interactive-pricing-component",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/pricing-component-with-toggle.webp",
    name: "Pricing component with toggle",
    techList: ["React", "Scss"],
    liveLink: "https://pricing-component-with-toggle-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/pricing-component-with-toggle",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/fylo-dark-theme-landing-page.webp",
    name: "Fylo dark theme landing page",
    techList: ["React", "Scss"],
    liveLink: "https://fylo-dark-theme-landing-page-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/fylo-dark-theme-landing-page",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/insure-landing-page.webp",
    name: "Insure landing page",
    techList: ["React", "Scss"],
    liveLink: "https://insure-landing-page-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/insure-landing-page",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/maker-pre-launch-landing-page.webp",
    name: "Maker pre-launch landing page",
    techList: ["React", "Scss"],
    liveLink: "https://maker-pre-launch-landing-page-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/maker-pre-launch-landing-page",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/project-tracking-intro-component.webp",
    name: "Project tracking intro component",
    techList: ["React", "Scss"],
    liveLink: "https://project-tracking-intro-component-ten.vercel.app/",
    gitRepo: "https://github.com/a1conwf/project-tracking-intro-component",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/news-homepage.webp",
    name: "News homepage",
    techList: ["React", "Scss"],
    liveLink: "https://news-homepage-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/news-homepage",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/advice-generator-app.webp",
    name: "Advice generator app",
    techList: ["React", "Scss", "Api"],
    liveLink: "https://advice-generator-app-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/advice-generator-app",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/loopstudios-landing-page.webp",
    name: "Loopstudios landing page",
    techList: ["React", "Scss"],
    liveLink: "https://loopstudios-landing-page-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/loopstudios-landing-page",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/sunnyside-agency-landing-page.webp",
    name: "Sunnyside agency landing page",
    techList: ["React", "Scss"],
    liveLink: "https://sunnyside-agency-landing-page-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/sunnyside-agency-landing-page",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/art-gallery-website.webp",
    name: "Art gallery website",
    techList: ["React", "Scss"],
    liveLink: "https://art-gallery-website-a1conwf.vercel.app/",
    gitRepo: "https://github.com/a1conwf/art-gallery-website",
  },
  {
    id: nanoid(),
    img: "/src/assets/img/single-page-design-portfolio.webp",
    name: "Single-page design portfolio",
    techList: ["Html", "Scss", "Javascript"],
    liveLink: "https://a1conwf.github.io/single-page-design-portfolio/",
    gitRepo: "https://github.com/a1conwf/single-page-design-portfolio",
  },
];
